apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-notebooks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
